# Generated by Django 4.2.7 on 2023-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='government_id',
            field=models.TextField(),
        ),
    ]
