# Generated by Django 4.2.7 on 2023-11-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0003_alter_driver_government_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('completed', 'Completed'), ('in_process', 'In process'), ('declined', 'Declined')], default='in_process'),
        ),
    ]
