# Generated by Django 4.2.7 on 2023-11-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0004_delete_route_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('posted', 'Posted'), ('completed', 'Completed'), ('in_progress', 'In progress'), ('declined', 'Declined')], default='posted'),
        ),
    ]
