# Generated by Django 4.2.7 on 2023-11-14 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateTaken',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 18, 12, 17, 525490, tzinfo=datetime.timezone.utc)),
        ),
    ]
