# Generated by Django 4.2.7 on 2023-11-14 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0006_task_datetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateTaken',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 18, 12, 57, 590762, tzinfo=datetime.timezone.utc)),
        ),
    ]
