# Generated by Django 4.2.7 on 2023-11-14 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0007_alter_task_datetaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateTaken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
