# Generated by Django 4.2.7 on 2023-11-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0008_alter_task_datetaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
