# Generated by Django 4.2.7 on 2023-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0009_remove_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
