# Generated by Django 4.2.7 on 2023-11-28 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0010_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('posted', 'Posted'), ('completed', 'Completed'), ('declined', 'Declined')], default='posted'),
        ),
        migrations.CreateModel(
            name='FuelingInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gas_station_name', models.TextField()),
                ('fuel_amount', models.FloatField()),
                ('total_fuel_cost', models.FloatField()),
                ('image_before_fueling', models.ImageField(upload_to='fueling/')),
                ('image_after_fueling', models.ImageField(upload_to='fueling/')),
                ('fueling_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.fuelingperson')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_app.vehicle')),
            ],
        ),
    ]
