# Generated by Django 4.2.7 on 2023-11-28 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0011_alter_task_status_fuelinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelinginfo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
